"use client";
import {useEffect,useState}from"react";
import {copy,featureLabel,localeFor,riskLabel}from"../i18n";
import {ForecastChart}from"../components/ForecastChart";import {Explainability}from"../components/Explainability";import {OrganizationTable}from"../components/OrganizationTable";import {ModelInformation}from"../components/ModelInformation";
const API=process.env.NEXT_PUBLIC_API_URL||"http://127.0.0.1:8000/api/v1";let redirecting=false;
const token=()=>{try{return JSON.parse(localStorage.getItem("medflow-demo-user")||"{}").access_token||""}catch{return ""}};
const loginRequired=()=>{if(redirecting)return;redirecting=true;localStorage.removeItem("medflow-demo-user");location.replace("/login")};
const get=async p=>{const r=await fetch(`${API}${p}`,{headers:{Authorization:`Bearer ${token()}`}});if(r.status===401){loginRequired();throw Error("unauthorized")}if(!r.ok)throw Error("api");return r.json()};
const Select=({label,value,onChange,children})=><label className="filter-control"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>;const Badge=({risk,t})=><span className={`risk risk-${risk}`}><i/>{riskLabel(risk,t)}</span>;const Sk=({className=""})=><div className={`skeleton ${className}`}/>;
export default function Page(){const[authorized,setAuthorized]=useState(false),[lang,setLang]=useState("ru"),[theme,setTheme]=useState("system"),[orgs,setOrgs]=useState([]),[regions,setRegions]=useState([]),[f,setF]=useState({region:"all",organization:"",days:"30",risk:"all"}),[history,setHistory]=useState([]),[forecast,setForecast]=useState(),[anomalies,setAnomalies]=useState([]),[allForecasts,setAllForecasts]=useState({}),[metrics,setMetrics]=useState(),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[debouncedSearch,setDebouncedSearch]=useState(""),[sort,setSort]=useState("risk"),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[paging,setPaging]=useState({total:0,total_pages:0}),[summary,setSummary]=useState({}),[tableLoading,setTableLoading]=useState(true),[signalLoading,setSignalLoading]=useState(true),[signalSize,setSignalSize]=useState(25),[signalPage,setSignalPage]=useState(1),[signalPaging,setSignalPaging]=useState({total:0,total_pages:0});const t=copy[lang],locale=localeFor(lang),num=v=>v==null?"—":new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(v),date=v=>v?new Intl.DateTimeFormat(locale,{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${v}T00:00:00`)):"—";const change=(k,v)=>setF(x=>({...x,[k]:v}));
useEffect(()=>{if(!token()){loginRequired();return}const p=new URLSearchParams(location.search),saved=localStorage.getItem("medflow-language");setLang((["ru","en","kk"].includes(p.get("lang")||saved)?p.get("lang")||saved:"ru"));setTheme(localStorage.getItem("medflow-theme")||"system");get("/auth/me").then(()=>{setAuthorized(true);return Promise.all([get("/regions"),get("/metrics"),get("/summary")])}).then(([r,m,k])=>{setRegions(r);setMetrics(m);setSummary(k)}).catch(error=>{if(error.message!=="unauthorized")setError(t.apiError)}).finally(()=>setLoading(false))},[]);
useEffect(()=>{localStorage.setItem("medflow-language",lang);document.documentElement.lang=lang;const p=new URLSearchParams(location.search);p.set("lang",lang);window.history.replaceState({},"",`?${p}`)},[lang]);useEffect(()=>{localStorage.setItem("medflow-theme",theme);document.documentElement.dataset.theme=theme==="system"?(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"):theme},[theme]);useEffect(()=>{if(!f.organization){setForecast(undefined);setHistory([]);setDetailLoading(false);return}const p=new URLSearchParams({...f,lang});window.history.replaceState({},"",`?${p}`);let active=true;setForecast(undefined);setHistory([]);setDetailLoading(true);setError("");Promise.all([get(`/forecasts/${encodeURIComponent(f.organization)}`),get(`/organizations/${encodeURIComponent(f.organization)}/history?days=${f.days}`)]).then(([a,b])=>{if(active){setForecast(a);setHistory(b)}}).catch(()=>{if(active)setError(t.detailError)}).finally(()=>{if(active)setDetailLoading(false)});return()=>{active=false}},[f.organization,f.days]);
useEffect(()=>{const timer=setTimeout(()=>setDebouncedSearch(search),250);return()=>clearTimeout(timer)},[search]);
useEffect(()=>{setPage(1)},[f.region,f.risk,debouncedSearch,sort,pageSize]);
useEffect(()=>{if(!authorized)return;let active=true;setTableLoading(true);const q=new URLSearchParams({page:String(page),page_size:String(pageSize),sort,search:debouncedSearch});if(f.region!=="all")q.set("region_id",f.region);if(f.risk!=="all")q.set("risk",f.risk);get(`/organizations?${q}`).then(async data=>{if(!active)return;setOrgs(data.items);setPaging(data);setF(x=>({...x,organization:data.items.some(o=>o.id===x.organization)?x.organization:data.items[0]?.id||""}));const forecasts=await Promise.all(data.items.map(o=>get(`/forecasts/${encodeURIComponent(o.id)}?horizon_days=1`).catch(()=>null)));if(active)setAllForecasts(Object.fromEntries(forecasts.filter(Boolean).map(x=>[x.organization_id,x])))}).catch(error=>{if(active&&error.message!=="unauthorized")setError(t.apiError)}).finally(()=>{if(active)setTableLoading(false)});return()=>{active=false}},[authorized,page,pageSize,f.region,f.risk,debouncedSearch,sort]);
useEffect(()=>{setSignalPage(1)},[f.organization,f.days,signalSize]);
useEffect(()=>{if(!f.organization){setAnomalies([]);setSignalLoading(false);return}let active=true;setSignalLoading(true);get(`/anomalies?organization_id=${encodeURIComponent(f.organization)}&page=${signalPage}&page_size=${signalSize}`).then(x=>{if(active){setAnomalies(x.items);setSignalPaging(x)}}).catch(()=>{if(active)setError(t.detailError)}).finally(()=>{if(active)setSignalLoading(false)});return()=>{active=false}},[signalPage,signalSize,f.organization]);
const regionName=id=>regions.find(x=>x.id===id)?.name||`Неизвестный регион (код ${id})`,scoped=orgs,rows=orgs;const selected=orgs.find(x=>x.id===f.organization),delta=forecast&&selected?forecast.expected-(selected.latest_daily_registrations??0):null;const setRegion=v=>change("region",v);
const pager=(current,pages,total,update)=><div className="pagination"><button disabled={current<=1} onClick={()=>update(current-1)}>← Previous</button><span>{current} / {Math.max(1,pages)} · Всего: {num(total)}</span><button disabled={current>=pages} onClick={()=>update(current+1)}>Next →</button></div>;

return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#overview"><b>+</b>MedFlow <em>AI</em></a><nav aria-label={t.nav}><a className="active" href="#overview">▦ {t.overview}</a><a href="#regions">◌ {t.regions}</a><a href="#organizations">▤ {t.orgs}</a><a href="#risks">! {t.risks}</a><a href="#model">◈ {t.model}</a></nav><div className="sidebar-note"><span className="live-dot"/>{t.demo}<small>{t.demoDesc}</small></div></aside><main><header><div><p className="eyebrow">{t.ops}</p><h1>{t.overview}</h1><p className="subtitle">{t.subtitle}</p></div><div className="header-actions"><button onClick={async()=>{await fetch(`${API}/auth/logout`,{method:"POST",headers:{Authorization:`Bearer ${JSON.parse(localStorage.getItem("medflow-demo-user")||"{}").access_token}`}});localStorage.removeItem("medflow-demo-user");location.href="/login"}}>Выйти</button><Select label={t.language} value={lang} onChange={setLang}><option value="kk">🇰🇿 Қазақша</option><option value="ru">🇷🇺 Русский</option><option value="en">🇬🇧 English</option></Select><Select label={t.theme} value={theme} onChange={setTheme}><option value="light">☀ {t.light}</option><option value="dark">◐ {t.dark}</option><option value="system">◌ {t.system}</option></Select></div></header><div className="disclaimer"><strong>Локальная аналитика.</strong> {t.disclaimer}</div>{error&&<div className="error"><strong>{t.unavailableData}.</strong> {error}</div>}
<section className="filter-bar"><div className="filter-title"><b>{t.filters}</b><small>{t.instant}</small></div><Select label="Регион происхождения пациентов" value={f.region} onChange={setRegion}><option value="all">{t.allRegions}</option>{regions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label={t.org} value={f.organization} onChange={v=>change("organization",v)}><option value="">{t.noData}</option>{scoped.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label={t.period} value={f.days} onChange={v=>change("days",v)}>{[7,30,84].map(x=><option key={x} value={x}>{x} {t.days}</option>)}</Select><Select label={t.risk} value={f.risk} onChange={v=>change("risk",v)}><option value="all">{t.allRisks}</option>{["low","medium","high","critical"].map(x=><option key={x} value={x}>{riskLabel(x,t)}</option>)}</Select><button className="clear" onClick={()=>{setF({region:"all",organization:orgs[0]?.id||"",days:"30",risk:"all"});setSearch("")}}>{t.clear}</button></section>
<section className="kpis">{loading?[1,2,3,4].map(x=><Sk key={x} className="kpi"/>):<><article className="kpi"><span>{t.waiting}</span><strong>{num(summary.waiting)}</strong><small>{t.across.replace("{count}",summary.organizations)}</small></article><article className="kpi"><span>{t.attention}</span><strong>{num(summary.attention)}</strong><small>{t.highCritical}</small></article><article className="kpi"><span>{t.signals}</span><strong>{detailLoading?"—":signalPaging.total}</strong><small>{t.selected}</small></article><article className="kpi"><span>{t.horizon}</span><strong>{forecast?`${forecast.horizon_days} ${t.days}`:"—"}</strong><small>{forecast?.model||t.loading}</small></article></>}</section>
<section className="forecast-layout" id="overview"><article className="panel forecast-panel"><div className="panel-head"><div><p className="eyebrow">{t.forecast}</p><h2>{t.trend}</h2></div><span className="updated">{t.updated}: {date(history.at(-1)?.date)}</span></div><div className="forecast-summary"><div><span title="Число записей в исходном снимке очереди">{t.waiting}</span><b>{num(selected?.latest_waiting)}</b></div><div><span>{t.forecast}</span><b>{num(forecast?.expected)}</b></div><div><span title="Прогноз минус регистрации за последний наблюдаемый день">{t.change}</span><b className={delta>0?"negative":"positive"}>{delta==null?"—":`${delta>0?"+":""}${num(delta)}`}</b></div><div><span>{t.risk}</span>{selected?<Badge risk={selected.risk} t={t}/>:"—"}</div></div>{detailLoading?<Sk className="chart-skeleton"/>:<ForecastChart history={history} forecast={forecast} labels={t} locale={locale}/>}</article><Explainability forecast={forecast} loading={detailLoading} t={t} labelFor={x=>featureLabel(x,lang)}/></section>
<section className="panel regions" id="regions"><p className="eyebrow">{t.regional}</p><h2>{t.regions}</h2><div className="region-grid">{regions.map(r=><article key={r.id}><span>{r.name}</span><strong>{num(r.waiting)}</strong><small>{t.waiting} · {num(r.organization_count)} {t.orgs.toLowerCase()}</small></article>)}</div></section><section className="panel table-panel" id="organizations"><div className="panel-head"><div><p className="eyebrow">{t.network}</p><h2>{t.orgs}</h2></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/></div><select aria-label="Размер страницы" value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[25,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select>{tableLoading?<p aria-live="polite">{t.loading}</p>:<OrganizationTable rows={rows} forecasts={allForecasts} regionName={regionName} selected={f.organization} onSelect={v=>change("organization",v)} sort={sort} setSort={setSort} number={num} t={t} RiskBadge={Badge}/>} {pager(page,paging.total_pages,paging.total,setPage)}</section><section className="panel risk-panel" id="risks"><div className="panel-head"><div><p className="eyebrow">{t.warning}</p><h2>{t.anomalies}</h2></div>{selected&&<Badge risk={selected.risk} t={t}/>}</div>{detailLoading||signalLoading?<Sk className="empty-skeleton"/>:anomalies.length?<div className="alerts">{anomalies.map(x=><article className={`alert alert-${x.severity}`} key={x.date}><Badge risk={x.severity} t={t}/><div><strong>{date(x.date)} · {t.historical}</strong><p>{x.explanation}</p></div><dl><div><dt>{t.observed}</dt><dd>{num(x.observed)}</dd></div><div><dt>{t.expected}</dt><dd>{num(x.expected)}</dd></div></dl></article>)}</div>:<div className="empty"><strong>{t.noAnomalies}</strong><span>{t.noAnomaliesDesc}</span></div>}</section><select aria-label="Размер страницы сигналов" value={signalSize} onChange={e=>setSignalSize(Number(e.target.value))}>{[25,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select>{pager(signalPage,signalPaging.total_pages,signalPaging.total,setSignalPage)}<ModelInformation metrics={metrics} t={t} lang={lang}/><footer>{t.decision}</footer></main></div>}
