"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {ForecastChart} from "../components/ForecastChart";
import {Explainability} from "../components/Explainability";
import {ModelInformation} from "../components/ModelInformation";

const API=process.env.NEXT_PUBLIC_API_URL||"/api/v1";
let clientReady=false;
const session=()=>{if(!clientReady)return {};try{return JSON.parse(localStorage.getItem("medflow-demo-user")||"{}")}catch{return {}}};
const headers=()=>({Authorization:`Bearer ${session().access_token||""}`,"Content-Type":"application/json"});
async function api(path,options={}){let response;try{response=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}})}catch{throw Object.assign(new Error("Backend недоступен"),{code:"BACKEND_OFFLINE"})}if(response.status===401){localStorage.removeItem("medflow-demo-user");location.replace("/login");throw Error("AUTH_REQUIRED")}if(!response.ok){const body=await response.json().catch(()=>({}));throw Object.assign(new Error(body.error?.message||body.detail||"Ошибка API"),{code:body.error?.code||"API_ERROR"})}return response;}
const json=async(path,options)=>api(path,options).then(r=>r.json());
const number=v=>v==null?"—":new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1}).format(v);
const date=v=>v?new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium"}).format(new Date(`${v}T00:00:00`)):"—";
const riskText={normal:"Норма",attention:"Внимание",high:"Высокий",critical:"Критический",low:"Норма",medium:"Внимание"};
const Badge=({level})=><span className={`risk risk-${level}`}><i aria-hidden="true"/>{riskText[level]||level}</span>;
const Skeleton=({className=""})=><div className={`skeleton ${className}`} aria-label="Загрузка"/>;
const ACTIONS=[['prescription_draft','Сформировать проект предписания'],['flow_redirect','Подготовить перенаправление потока'],['notify_chief','Уведомить главного врача'],['add_control','Добавить в контроль'],['report','Сформировать отчёт']];

function StatusStrip({health,sources}){const items=[['API',health?.components?.api],['Данные',health?.components?.dataset],['ML',health?.components?.model],['Хранилище',health?.components?.database]];return <div className="status-strip">{items.map(([name,item])=><div key={name}><span className={`status-dot ${['online','available','ready'].includes(item?.status)?'ok':'bad'}`}/><b>{name}</b><small>{item?.status||'проверка'}</small></div>)}<div><span className="status-dot ok"/><b>Актуальность</b><small>{sources?.items?.[0]?.freshness||'пакетная выгрузка'}</small></div></div>}

function KazakhstanMap({regions,selected,onSelect}){const[shapes,setShapes]=useState([]);useEffect(()=>{fetch('/kazakhstan-regions.json').then(r=>r.json()).then(setShapes).catch(()=>setShapes([]))},[]);const byId=Object.fromEntries(regions.map(x=>[x.id,x]));return <div className="map-layout"><div className="map-card"><svg viewBox="0 0 610 300" role="img" aria-label="Интерактивная карта административных регионов Казахстана">{shapes.map(shape=>{const id=shape.pcode.slice(2),r=byId[id],active=selected===id;return <g key={id} role="button" tabIndex="0" aria-label={`${r?.name||shape.name_kk}: ${riskText[r?.risk_level]||'нет данных'}`} onClick={()=>onSelect(id)} onKeyDown={e=>['Enter',' '].includes(e.key)&&onSelect(id)}><path d={shape.path} className={`map-region map-${r?.risk_level||'empty'} ${active?'selected':''}`}><title>{r?.name||shape.name_kk} — очередь {number(r?.current_waiting)}, прогноз {number(r?.predicted_daily_registrations)}/день, риск {riskText[r?.risk_level]||'нет данных'}</title></path>{shape.cx&&<text x={shape.cx} y={shape.cy}>{id}</text>}</g>})}</svg><div className="map-legend" aria-label="Легенда риска">{['normal','attention','high','critical'].map(x=><span key={x}><i className={`legend-${x}`}/>{riskText[x]}</span>)}</div><small>Границы: new_qazaqstan_GeoJSON, 2024 (MIT), локальный static asset. Коды связаны только через проверенный KATO mapping.</small></div>{selected&&<RegionalPanel region={byId[selected]} onClose={()=>onSelect('')}/>}</div>}
function RegionalPanel({region,onClose}){if(!region)return null;return <aside className="regional-panel"><button className="icon-button" onClick={onClose} aria-label="Закрыть">×</button><p className="eyebrow">Региональный срез</p><h3>{region.name}</h3><Badge level={region.risk_level}/><dl className="metric-list"><div><dt>Текущая очередь</dt><dd>{number(region.current_waiting)}</dd></div><div><dt>Прогноз регистраций/день</dt><dd>{number(region.predicted_daily_registrations)}</dd></div><div><dt>Организации</dt><dd>{number(region.organization_count)}</dd></div><div><dt>Высокий риск</dt><dd>{number(region.high_risk_organizations)}</dd></div><div><dt>Аномалии</dt><dd>{number(region.anomaly_count)}</dd></div></dl><small>Данные на {date(region.data_freshness)}</small></aside>}

function ActionModal({organization,forecast,onClose,onSaved}){const[action,setAction]=useState(ACTIONS[0][0]),[comment,setComment]=useState(''),[saving,setSaving]=useState(false),risk=organization?.risk_assessment;if(!organization)return null;const submit=async()=>{setSaving(true);try{await json('/actions',{method:'POST',body:JSON.stringify({organization_id:organization.id,action_type:action,reason:comment,model_version:forecast.model_version,forecast_snapshot:{expected:forecast.expected,lower:forecast.lower,upper:forecast.upper,risk_level:risk.risk_level,risk_score:risk.risk_score}})});onSaved();onClose()}finally{setSaving(false)}};return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="action-title"><button className="icon-button" onClick={onClose}>×</button><p className="eyebrow">Human-in-the-loop</p><h2 id="action-title">Проект управленческого действия</h2><div className="modal-summary"><b>{organization.name}</b><span>{organization.region_name}</span><p>{risk.reasons.join('. ')}</p><div><span>Очередь: <b>{number(organization.latest_waiting)}</b></span><span>Прогноз/день: <b>{number(forecast.expected)}</b></span><Badge level={risk.risk_level}/></div></div><label>Предлагаемое действие<select value={action} onChange={e=>setAction(e.target.value)}>{ACTIONS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Комментарий пользователя<textarea rows="4" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Основание, контекст и что необходимо проверить"/></label><div className="notice"><b>Важно:</b> создаётся черновик. Система не выполняет административное действие автоматически.</div><div className="modal-actions"><button className="secondary" onClick={onClose}>Отмена</button><button className="primary" disabled={saving} onClick={submit}>{saving?'Сохранение…':'Подтвердить и сохранить черновик'}</button></div></section></div>}

function DataSources({data}){return <section className="panel" id="sources"><div className="panel-head"><div><p className="eyebrow">DATA PROVENANCE</p><h2>Источники данных</h2></div><span className="health-chip">Data Health: {data?.health?.status==='healthy'?'доступны':'требует внимания'}</span></div><p className="section-note">Пакетные файловые выгрузки. Real-time интеграция не подключена.</p><div className="source-grid">{data?.items?.map(x=><article key={x.id}><div><span className={`status-dot ${x.status==='available'?'ok':'bad'}`}/><b>{x.source}</b></div><p>{x.dataset}</p><dl><div><dt>Записей</dt><dd>{number(x.records_processed)}</dd></div><div><dt>Период</dt><dd>{x.dataset_period?.join(' — ')||'не определён'}</dd></div><div><dt>Проверка</dt><dd>{x.validation_status}</dd></div></dl><small>{x.warnings?.join(' · ')}</small></article>)}</div></section>}

function ActionsLog({items,reload}){const change=async(id,status)=>{await json(`/actions/${id}`,{method:'PATCH',body:JSON.stringify({status})});reload()};return <section className="panel" id="actions"><div className="panel-head"><div><p className="eyebrow">DECISION SUPPORT</p><h2>Журнал управленческих решений</h2></div><span className="muted">Решения подтверждаются человеком</span></div><div className="table-wrap compact"><table><thead><tr><th>Создано</th><th>Организация</th><th>Действие</th><th>Основание</th><th>Статус</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('ru-RU')}</td><td>{x.organization_id}</td><td>{ACTIONS.find(a=>a[0]===x.action_type)?.[1]||x.action_type}</td><td>{x.reason||'—'}</td><td><select value={x.status} onChange={e=>change(x.id,e.target.value)}>{['draft','approved','rejected','completed'].map(s=><option key={s}>{s}</option>)}</select></td></tr>):<tr><td colSpan="5" className="empty-cell">Решения ещё не созданы</td></tr>}</tbody></table></div></section>}

export default function Dashboard(){const[loading,setLoading]=useState(true),[error,setError]=useState(null),[health,setHealth]=useState(),[summary,setSummary]=useState({}),[regions,setRegions]=useState([]),[sources,setSources]=useState(),[model,setModel]=useState(),[organizations,setOrganizations]=useState([]),[paging,setPaging]=useState({}),[filters,setFilters]=useState({region:'',risk:'',search:'',page:1,page_size:25}),[selectedId,setSelectedId]=useState(''),[selected,setSelected]=useState(),[forecast,setForecast]=useState(),[explain,setExplain]=useState(),[history,setHistory]=useState([]),[anomalies,setAnomalies]=useState([]),[actions,setActions]=useState([]),[modal,setModal]=useState(false),[report,setReport]=useState(),[toast,setToast]=useState('');
const loadBase=useCallback(async()=>{setError(null);setLoading(true);try{const[h,s,r,d,m,a]=await Promise.all([json('/health'),json('/summary'),json('/regions'),json('/data-sources'),json('/model/info'),json('/actions')]);setHealth(h);setSummary(s);setRegions(r);setSources(d);setModel(m);setActions(a.items)}catch(e){setError({code:e.code,message:e.message})}finally{setLoading(false)}},[]);
const loadActions=useCallback(()=>json('/actions').then(x=>setActions(x.items)),[]);
useEffect(()=>{clientReady=true;const current=session();if(!current.access_token){location.replace('/login');return}loadBase()},[loadBase]);
useEffect(()=>{let active=true;const q=new URLSearchParams({page:String(filters.page),page_size:String(filters.page_size),sort:'risk'});if(filters.region)q.set('region_id',filters.region);if(filters.risk)q.set('risk',filters.risk);if(filters.search)q.set('search',filters.search);json(`/organizations?${q}`).then(x=>{if(!active)return;setOrganizations(x.items);setPaging(x);setSelectedId(id=>x.items.some(o=>o.id===id)?id:(x.items[0]?.id||''))}).catch(e=>setError({code:e.code,message:e.message}));return()=>{active=false}},[filters]);
useEffect(()=>{if(!selectedId)return;Promise.all([json(`/organizations/${encodeURIComponent(selectedId)}`),json(`/organizations/${encodeURIComponent(selectedId)}/forecast`),json(`/model/explain/${encodeURIComponent(selectedId)}`),json(`/organizations/${encodeURIComponent(selectedId)}/history?days=30`),json(`/anomalies?organization_id=${encodeURIComponent(selectedId)}&page_size=25`)]).then(([o,f,e,h,a])=>{setSelected(o);setForecast(f);setExplain(e);setHistory(h);setAnomalies(a.items)}).catch(e=>setError({code:e.code,message:e.message}))},[selectedId]);
const updateFilter=(key,value)=>setFilters(f=>({...f,[key]:value,page:1}));const selectedRegion=filters.region;const highOrCritical=selected?.risk_assessment&&['high','critical'].includes(selected.risk_assessment.risk_level);
const createReport=async()=>{const x=await json('/reports',{method:'POST',body:JSON.stringify({region_id:filters.region||null,organization_id:null,risk:filters.risk||null,period_days:30})});setReport(x);setToast('Управленческий отчёт сформирован')};
const download=async format=>{if(!report)return;const response=await api(`/reports/${report.id}/export/${format}`);const blob=await response.blob(),url=URL.createObjectURL(blob);if(['print','pdf'].includes(format)){window.open(url,'_blank')}else{const a=document.createElement('a');a.href=url;a.download=`${report.id}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}};
const logout=async()=>{await api('/auth/logout',{method:'POST'}).catch(()=>{});localStorage.removeItem('medflow-demo-user');location.href='/login'};
return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#overview"><span>MF</span><div>MedFlow <b>AI</b><small>Ситуационный центр</small></div></a><nav aria-label="Основная навигация">{[['overview','Обзор'],['map','Карта нагрузки'],['organizations','Медицинские организации'],['forecast','Прогнозирование'],['anomalies','Аномалии'],['actions','Управленческие решения'],['reports','Отчётность'],['sources','Источники данных'],['model','Информация о модели']].map(([id,label],i)=><a key={id} href={`#${id}`}><i>{String(i+1).padStart(2,'0')}</i>{label}</a>)}</nav><div className="sidebar-footer"><b>{session().demo?'ДЕМО ЭЦП':'Администратор'}</b><small>{session().demo?'Без интеграции НУЦ РК':session().email}</small></div></aside><main><header className="topbar"><div><p className="eyebrow">МИНИСТЕРСТВО ЗДРАВООХРАНЕНИЯ · АНАЛИТИЧЕСКИЙ КОНТУР</p><h1>Мониторинг госпитализации</h1><p>Нагрузка стационаров, прогноз дневных регистраций и поддержка решений</p></div><div className="top-actions"><button className="secondary" onClick={loadBase}>↻ Обновить</button><button className="avatar" onClick={logout} title="Выйти">АД</button></div></header>{toast&&<div className="toast" role="status" onAnimationEnd={()=>setToast('')}>{toast}</div>}{error&&<div className="error-state"><div><b>{error.code==='BACKEND_OFFLINE'?'Backend недоступен':error.code==='MODEL_NOT_READY'?'Модель не обучена/не загружена':error.code==='DATA_UNAVAILABLE'?'Источник данных недоступен':'Не удалось загрузить данные'}</b><span>{error.message}</span></div><button className="primary" onClick={loadBase}>Повторить</button></div>}<StatusStrip health={health} sources={sources}/>
<section className="filters"><label>Регион происхождения<select value={filters.region} onChange={e=>updateFilter('region',e.target.value)}><option value="">Все регионы</option>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Уровень риска<select value={filters.risk} onChange={e=>updateFilter('risk',e.target.value)}><option value="">Все уровни</option>{['normal','attention','high','critical'].map(r=><option key={r} value={r}>{riskText[r]}</option>)}</select></label><label>Поиск организации<input value={filters.search} onChange={e=>updateFilter('search',e.target.value)} placeholder="Наименование или код"/></label><button onClick={()=>setFilters({region:'',risk:'',search:'',page:1,page_size:25})}>Сбросить</button></section>
<section id="overview"><div className="section-title"><div><p className="eyebrow">ОБЗОР</p><h2>Операционная картина</h2></div><span>Данные на {date(summary.data_as_of)}</span></div><div className="kpis">{loading?[1,2,3,4,5].map(x=><Skeleton className="kpi" key={x}/>):<><article className="kpi"><span>Текущая очередь</span><strong>{number(summary.waiting)}</strong><small>снимок, не прогноз</small></article><article className="kpi accent"><span>Прогноз новых регистраций</span><strong>{number(summary.predicted_daily_registrations)}</strong><small>на следующий день</small></article><article className="kpi"><span>Высокий риск</span><strong>{number(summary.attention)}</strong><small>организаций</small></article><article className="kpi"><span>Аномалии</span><strong>{number(summary.anomalies)}</strong><small>требуют проверки</small></article><article className="kpi"><span>Охват</span><strong>{number(summary.organizations)}</strong><small>организаций</small></article></>}</div><div className="callout"><b>Decision Support</b><span>Прогноз новых дневных регистраций не является прогнозом общего размера очереди. Рекомендации требуют решения ответственного специалиста.</span></div></section>
<section className="panel" id="map"><div className="panel-head"><div><p className="eyebrow">GIS · КАЗАХСТАН</p><h2>Карта нагрузки</h2></div><span className="muted">Выберите регион для фильтрации</span></div><KazakhstanMap regions={regions} selected={selectedRegion} onSelect={id=>updateFilter('region',id)}/></section>
<section className="panel" id="organizations"><div className="panel-head"><div><p className="eyebrow">МОНИТОРИНГ СЕТИ</p><h2>Медицинские организации</h2></div><label>Строк<select value={filters.page_size} onChange={e=>updateFilter('page_size',Number(e.target.value))}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Организация</th><th>Регион происхождения</th><th>Очередь сейчас</th><th>Прогноз регистраций/день</th><th>Риск</th><th>Балл</th></tr></thead><tbody>{organizations.map(o=><tr key={o.id} className={selectedId===o.id?'selected':''} onClick={()=>setSelectedId(o.id)}><td><b>{o.name}</b></td><td>{regions.find(r=>r.id===o.region_id)?.name||'Неизвестный регион'}</td><td>{number(o.latest_waiting)}</td><td>{number(o.predicted_daily_registrations)}</td><td><Badge level={o.risk}/></td><td><b>{o.risk_score}</b>/100</td></tr>)}</tbody></table></div><div className="pagination"><button disabled={filters.page<=1} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}>← Назад</button><span>Страница {paging.page||1} из {paging.total_pages||1} · {number(paging.total)} записей</span><button disabled={filters.page>=paging.total_pages} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}>Далее →</button></div></section>
<section id="forecast" className="detail-grid">{forecast&&<><article className="panel"><div className="panel-head"><div><p className="eyebrow">ПРОГНОЗИРОВАНИЕ</p><h2>{selected?.name}</h2></div><Badge level={selected?.risk_assessment?.risk_level}/></div><div className="forecast-summary"><div><span>Текущая очередь</span><b>{number(selected?.latest_waiting)}</b></div><div><span>Последний дневной поток</span><b>{number(selected?.latest_daily_registrations)}</b></div><div><span>Прогноз на завтра</span><b>{number(forecast.expected)}</b></div><div><span>MAE модели</span><b>±{number(forecast.error_mae)}</b></div></div><ForecastChart history={history} forecast={forecast} labels={{trend:'Динамика регистраций',historical:'Факт: регистрации/день',forecast:'Прогноз регистраций/день',interval:'95% интервал',boundary:'Начало прогноза'}} locale="ru-RU"/></article><Explainability forecast={{...forecast,explanation:explain?.contributions,uncertainty_method:forecast.uncertainty_method}} loading={!explain} t={{why:'Почему такой прогноз?',increases:'Повышает прогноз',decreases:'Снижает прогноз'}} labelFor={x=>explain?.contributions?.find(i=>i.feature===x)?.label||'Фактор модели'}/></>}<article className="panel risk-card"><p className="eyebrow">RISK ENGINE · НЕ МОДЕЛЬ</p><h2>Почему такой риск?</h2><div className="risk-score"><strong>{selected?.risk_assessment?.risk_score??'—'}</strong><span>/100</span><Badge level={selected?.risk_assessment?.risk_level}/></div><ul>{selected?.risk_assessment?.reasons?.map(x=><li key={x}>{x}</li>)}</ul><h3>Что проверить человеку</h3><ul className="checks">{selected?.risk_assessment?.recommended_checks?.map(x=><li key={x}>✓ {x}</li>)}</ul>{highOrCritical&&<button className="primary full" onClick={()=>setModal(true)}>Перейти к управленческому действию</button>}</article></section>
<section className="panel" id="anomalies"><div className="panel-head"><div><p className="eyebrow">КОНТРОЛЬ КАЧЕСТВА И ДИНАМИКИ</p><h2>Аномалии</h2></div><span>{anomalies.length} для выбранной организации</span></div>{anomalies.length?<div className="alert-list">{anomalies.map(x=><article key={x.date}><Badge level={x.severity}/><div><b>{date(x.date)}</b><p>{x.explanation}</p></div><span>Наблюдение {number(x.observed)} · ожидание {number(x.expected)} · z={x.z_score}</span></article>)}</div>:<div className="empty-state"><b>Статистических аномалий не обнаружено</b><span>Это не исключает операционный риск; проверьте причины risk score отдельно.</span></div>}</section>
<ActionsLog items={actions} reload={loadActions}/>
<section className="panel" id="reports"><div className="panel-head"><div><p className="eyebrow">OFFICIAL REPORTING</p><h2>Отчётность и экспорт</h2></div><button className="primary" onClick={createReport}>Сформировать отчёт по фильтрам</button></div><p className="section-note">Отчёт учитывает активные регион и уровень риска. Проверка checksum демонстрационная и не является ЭЦП.</p>{report?<div className="report-card"><div><b>{report.id}</b><span>Сформирован {new Date(report.created_at).toLocaleString('ru-RU')}</span><code>{report.checksum}</code></div><div><button onClick={()=>download('csv')}>CSV</button><button onClick={()=>download('xlsx')}>XLSX</button><button onClick={()=>download('print')}>Печать / PDF</button></div></div>:<div className="empty-state">Сформируйте снимок отчёта для экспорта и DEMO verification.</div>}</section>
<DataSources data={sources}/><ModelInformation metrics={model} t={{transparency:'TRANSPARENCY',info:'Информация о модели'}} lang="ru"/><footer>MedFlow AI · Решения принимает человек после проверки первичных данных. Система не выполняет административные действия автоматически.</footer>{modal&&<ActionModal organization={selected} forecast={forecast} onClose={()=>setModal(false)} onSaved={()=>{loadActions();setToast('Черновик решения сохранён')}}/>}</main></div>}
